### ISSUE TITLE
Instruction dialog hits firefox layout bug

### ISSUE THREAD

**Issue by daniel-dressler** [chrisantonellis/gbtdg#3]
Sorry for not fixing this, I'm falling asleep as I'm writing this.

Congrats on the refactoring, the code looks better and the interface is cleaner as well.

We appear to be hitting a bug in firefox where child elements with position = absolute are not being confined by their position = relative parents. This only happens if the parent or the child uses a table style display, which we are with display = table-row.

Some suggested work arounds are mentioned here: https://stackoverflow.com/questions/17487974/css-absolute-div-inside-relative-parent-for-firefox

The easiest solution appears to be wrapping the position = absolute element in an extra div with said div's position = relative.

What do you think?

**Comment by chrisantonellis** [comment]
@daniel-dressler just returning to this repo after a loooong absence. are you still making use of this tool?

**Comment by daniel-dressler** [comment]
Haha, no. I last used this back in university.
