### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by pinobatch** [chrisantonellis/gbtdg#9]
The file `readme.md` links to <http://www.chrisantonellis.com/gameboy/gbtdg> which states: "We couldn't find the page you were looking for." It offers a link to a [search page](https://www.chrisantonellis.com/search), but the query `gbtdg` produces "Your search did not match any documents."

**Comment by amfl** [comment]
If the owner goes into the repo settings, they could enable [Github pages](https://pages.github.com/) to get Github to provide the hosting. It looks like [some forks are already doing this](https://500cc.github.io/gbtdg).

To turn it on:
- Click on the Settings tab and scroll down to the GitHub Pages section.
- Then select the master branch source and click on the Save button.

Then everything will be available at <https://chrisantonellis.github.io/gbtdg>.

**Comment by T0biasCZe** [comment]
its on web archive
https://web.archive.org/web/20180823062554/http://www.chrisantonellis.com:80/gameboy/gbtdg/#

**Comment by chrisantonellis** [comment]
the application is now deployed to github pages!
